# Generated by Django 4.2 on 2024-10-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', '매니저'), ('staff', '직원')], default='staff', max_length=10),
        ),
    ]
