# Generated by Django 4.2 on 2024-10-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CEO', '대표'), ('manager', '매니저'), ('designer', '디자이너'), ('user', '일반회원')], max_length=50),
        ),
    ]
