# Generated by Django 4.2 on 2024-10-04 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
            ],
            options={
                'verbose_name': '서비스 카테고리',
                'verbose_name_plural': '서비스 카테고리들',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='서비스명')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='기본 단가')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service.servicecategory', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '서비스',
                'verbose_name_plural': '서비스들',
            },
        ),
    ]
