# Generated by Django 4.2 on 2024-10-13 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedesigner',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storestaff'),
        ),
        migrations.AddField(
            model_name='servicedesigner',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
        migrations.AddField(
            model_name='servicedesigner',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='service',
            name='available_designers',
            field=models.ManyToManyField(related_name='designer_services', to='stores.storestaff'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.category'),
        ),
        migrations.AddField(
            model_name='service',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='assigned_designer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'designer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.storestaff'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.customer'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
