# Generated by Django 4.2 on 2024-10-08 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
