# Generated by Django 4.2 on 2024-10-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('service', '0003_alter_reservation_assigned_designer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='assigned_designer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['designer', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.storestaff'),
        ),
    ]
