# Generated by Django 4.2 on 2024-10-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_gender',
            field=models.CharField(blank=True, choices=[('M', '남'), ('F', '여')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
