# Generated by Django 4.2 on 2024-10-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_reservation_assigned_designer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='available_designers',
        ),
    ]
