# Generated by Django 4.2 on 2024-10-20 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_delete_managementcalendar'),
        ('service', '0006_service_available_designers'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='designer_sales',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='service_sales',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('예약 중', '예약 중'), ('예약 대기', '예약 대기'), ('예약 취소', '예약 취소'), ('방문 완료', '방문 완료')], max_length=20),
        ),
    ]
