# Generated by Django 4.2 on 2024-10-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_delete_managementcalendar'),
        ('service', '0007_salesreport_designer_sales_salesreport_service_sales_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesreport',
            unique_together={('store', 'date')},
        ),
    ]
