# Generated by Django 4.2 on 2024-10-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_remove_salesreport_designer_sales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='membership_status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='reservation_count',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer_gender',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer_phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_membership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='membership_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
