# Generated by Django 4.2 on 2024-10-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_remove_customer_membership_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_membership',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='membership_start_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='discounted_price',
        ),
        migrations.AddField(
            model_name='customer',
            name='membership_status',
            field=models.CharField(choices=[('일반 고객', '일반 고객'), ('멤버십 가입 고객', '멤버십 가입 고객')], default='일반 고객', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='reservation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_gender',
            field=models.CharField(blank=True, choices=[('M', '남'), ('F', '여')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
