# Generated by Django 4.2 on 2024-10-31 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_delete_managementcalendar'),
        ('service', '0012_customer_is_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(blank=True, help_text='고객 이름', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(help_text='서비스의 카테고리', on_delete=django.db.models.deletion.CASCADE, to='stores.category'),
        ),
    ]
