# Generated by Django 4.2 on 2024-10-13 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(default='unknown', max_length=255)),
                ('ceo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('designer', 'Designer'), ('manager', 'Manager')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('available_services', models.ManyToManyField(related_name='staff_available_services', to='service.service')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_staff', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_working', models.IntegerField(default=0)),
                ('total_off', models.IntegerField(default=0)),
                ('total_substitute', models.IntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('working', '근무 중'), ('off', '휴무')], default='working', max_length=10)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_calendar', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_calendar', to='stores.store')),
            ],
            options={
                'unique_together': {('staff', 'date')},
            },
        ),
        migrations.AddConstraint(
            model_name='storestaff',
            constraint=models.UniqueConstraint(fields=('store', 'user'), name='unique_store_user'),
        ),
        migrations.AlterUniqueTogether(
            name='managementcalendar',
            unique_together={('store', 'date')},
        ),
    ]
