# Generated by Django 4.2 on 2024-10-04 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managementcalendar',
            old_name='total_off',
            new_name='total_staff_off',
        ),
        migrations.RenameField(
            model_name='managementcalendar',
            old_name='total_substitute',
            new_name='total_staff_working',
        ),
        migrations.RemoveField(
            model_name='managementcalendar',
            name='total_working',
        ),
        migrations.AlterField(
            model_name='managementcalendar',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
