# Generated by Django 4.2 on 2024-10-18 06:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workcalendar',
            unique_together={('store', 'staff', 'date')},
        ),
    ]
