# Generated by Django 4.2 on 2024-10-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_rename_total_off_managementcalendar_total_staff_off_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managementcalendar',
            old_name='total_staff_off',
            new_name='total_off',
        ),
        migrations.RenameField(
            model_name='managementcalendar',
            old_name='total_staff_working',
            new_name='total_working',
        ),
    ]
