# Generated by Django 4.2 on 2024-10-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_rename_total_staff_off_managementcalendar_total_off_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementcalendar',
            name='total_substitute',
            field=models.IntegerField(default=0),
        ),
    ]
