# Generated by Django 4.2 on 2024-10-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_workcalendar_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagementCalendar',
        ),
    ]
