# Generated by Django 4.2 on 2024-10-04 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='공급업체명')),
                ('contact_person', models.CharField(max_length=100, verbose_name='담당자')),
                ('phone', models.CharField(max_length=20, verbose_name='전화번호')),
            ],
            options={
                'verbose_name': '공급업체',
                'verbose_name_plural': '공급업체들',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='개별 단가')),
                ('supply_date', models.DateField(verbose_name='납품 일자')),
                ('received_date', models.DateField(verbose_name='수령일')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='입금 일자')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='inventory.inventoryitem', verbose_name='재고 아이템')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='supplier.supplier', verbose_name='공급업체')),
            ],
            options={
                'verbose_name': '납품',
                'verbose_name_plural': '납품들',
            },
        ),
    ]
